version: '2'
services:
    traveloguegateway-app:
        image: traveloguegateway
        external_links:
            - traveloguegateway-mysql:mysql
            # Uncomment to have Cassandra working with the gateway
            # - traveloguegateway-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/traveloguegateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
        ports:
            - 8080:8080
    traveloguegateway-mysql:
        extends:
            file: mysql.yml
            service: traveloguegateway-mysql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: traveloguegateway-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
