version: '2'
services:
    travelogueresources-app:
        image: travelogueresources
        external_links:
            - travelogueresources-mongodb:mongodb
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=TravelogueResources
    travelogueresources-mongodb:
        extends:
            file: mongodb.yml
            service: travelogueresources-mongodb
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
