version: '2'
services:
    travelogueresources-mongodb:
        container_name: travelogueresources-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/TravelogueResources/mongodb/:/data/db/
