version: '2'
services:
    traveloguepost-app:
        image: traveloguepost
        external_links:
            - traveloguepost-mongodb:mongodb
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=TraveloguePost
    traveloguepost-mongodb:
        extends:
            file: mongodb.yml
            service: traveloguepost-mongodb
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
