version: '2'
services:
    traveloguepost-mongodb:
        container_name: traveloguepost-mongodb
        image: mongo:3.2.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/TraveloguePost/mongodb/:/data/db/
